# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 01:11
from __future__ import unicode_literals

from django.db import migrations
from myapp2 import models as app_models
import csv

def load_pre_existing_constants_in_db(apps, schema_editor):
    """
    :param apps:
    :param schema_editor:
    :return:
    """

    dataReader = csv.reader(open('C:\\JavaCode\\DIVA\\ScrapedData\\nbaplayernames.csv'))
    for row in dataReader:
        app_models.Player.objects.create(Player=row[0], Team=row[1], Age=row[2])


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
	migrations.RunPython(load_pre_existing_constants_in_db),
    ]
